// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wireless} from '../models';

export function SystemRead():Promise<string>;

export function SystemWrite(arg1:string):Promise<void>;

export function WirelessRead():Promise<wireless.Class>;

export function WirelessWrite(arg1:boolean,arg2:string,arg3:string):Promise<void>;
