// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SystemRead() {
  return window['go']['main']['App']['SystemRead']();
}

export function SystemWrite(arg1) {
  return window['go']['main']['App']['SystemWrite'](arg1);
}

export function WirelessRead() {
  return window['go']['main']['App']['WirelessRead']();
}

export function WirelessWrite(arg1, arg2, arg3) {
  return window['go']['main']['App']['WirelessWrite'](arg1, arg2, arg3);
}
